{% set name = "yell" %}
{% set version = "2.2.1" %}

package:
  name: rb-{{ name|lower }}
  version: {{ version }}

source:
  url: https://rubygems.org/downloads/{{ name }}-{{ version }}.gem
  sha256: 95cbe7e9b17557589ec76ff0dc5396447e96e887cf412ee56a78a400dbf353e4

build:
  noarch: generic
  number: 0
  script:
    - gem install -N -l -V --norc --ignore-dependencies {{ name }}-{{ version }}.gem
    - gem unpack {{ name }}-{{ version }}.gem
  skip: {{ win }}

requirements:
  host:
    - ruby
  run:
    - ruby

test:
  commands:
    - ruby -r {{ name }} -e 'exit 0'

about:
  home: https://rubygems.org/gems/{{ name }}
  license: MIT
  license_family: MIT
  license_file: {{ name }}-{{ version }}/LICENSE.txt
  summary: Yell - Your Extensible Logging Library. Define multiple adapters, various log level combinations or message formatting options like you've never done before

  doc_url: https://www.rubydoc.info/gems/{{ name }}
  dev_url: https://github.com/rudionrails/{{ name }}

extra:
  recipe-maintainers:
    - bgruening
    - sodre
