travis:
  secure:
    BINSTAR_TOKEN: RwO4XU4Udy4yhXor71d/95EYBX74R8Jll9/dGU6v2dd9rQ+kISQKvlOxCLEn9NOSuAZRMX8Qq7SbDFjpQeFJxQrzeK6CN51Nr0PBuMqnnBn789SePKKKThD91YfbQqXQIp9MuzuVrRLwnjk5vDKVPwaqZ5pFTjkeMGp8eRW5pXL1ZABn17h0cZ67Do9MO8ePCi8HUvqn2OsRqXe0er28tc9n7nzojmwYh3iunuhWb8dPjpToTSt9oS7BF+dAtN5J03XTAzpbd1/R/cv343hGEsj7r81vpo8Ffd/886WZQq3F8ebREu4EUih5nn1v0unIPPbqOrNdYJdwdcpu9tt7R6PwiN5227pMX2dktt6oxCxfTuQc6DJJaZBVmm0Hbx74Fwqbr/4UVo/Z1W2lBO6XKFgAZP/qEMFQz7cf8/+/u8DSNdLBbf86sgw2BrQ9rFPj2v0D0IInbj8HQdqZc81ilNw8HJaYZM061yxQpgA/Yj1Cp4dcZe0IvbPcitUCznCCjTGtN2jq/60B6OwimBcNBke9OA26h+fjzzBBemDnGvtrgmVdkVMpAovnHxB+/qBXlSNPgtXf6Ju3gAJ/am1yV5Aagluxqa7U5/IUdyVz9wuE4/mNNx0PYDKZTjSxh5FfvfvX4kTSqSLVLJ8eoxDOjnfoHLCyZT2a5tw1wUnD+sA=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
conda_forge_output_validation: true
